"""Automatic PR generator from GitHub Issues (uses the shared generator)."""

from __future__ import annotations

import os
import subprocess
import sys

from google import genai

import generator
import llm


def comment_on_issue(issue_number: str, body: str) -> None:
    subprocess.run(
        ["gh", "issue", "comment", issue_number, "--body", body],
        capture_output=True,
        text=True,
    )


def main() -> int:
    issue_number = os.environ.get("ISSUE_NUMBER")
    issue_title = os.environ.get("ISSUE_TITLE", "")
    issue_body = os.environ.get("ISSUE_BODY", "")

    if not issue_number:
        print("Error: ISSUE_NUMBER environment variable is required", file=sys.stderr)
        return 1
    if not os.environ.get("GEMINI_API_KEY") and not llm.proxy_enabled():
        print("Error: set GEMINI_API_KEY or LITELLM_BASE_URL", file=sys.stderr)
        return 1

    print(f"🚀 Processing Issue #{issue_number}: {issue_title}")
    client = genai.Client() if os.environ.get("GEMINI_API_KEY") else None
    via = "LiteLLM proxy" if llm.proxy_enabled() else "direct Gemini"
    print(f"🤖 Generating solution via {via} …")

    task = (
        f"Issue #{issue_number}: {issue_title}\n\n"
        f"Issue description:\n{issue_body}\n\n"
        f"Generate the file changes to resolve this issue. The pr_description "
        f"MUST end with 'Fixes #{issue_number}'."
    )
    try:
        data = generator.generate_changes(
            task=task,
            kind="issue",
            session=llm.session_id("issue", ref=issue_number),
            memory_scope="issue",
            genai_client=client,
        )
    except ValueError as exc:
        print(f"❌ {exc}", file=sys.stderr)
        return 1

    file_changes = data.get("file_changes", [])
    if not file_changes:
        print("⚠️ No file changes generated by the model.")
        return 0

    # If the model only proposed workflow files, we cannot push them; tell the
    # reporter instead of failing silently.
    kept, skipped = generator.filter_workflow_files(file_changes)
    if not kept:
        note = (
            f"🤖 I generated changes for this issue, but they only touched "
            f"GitHub Actions workflow files ({', '.join(skipped)}), which this "
            f"bot cannot push (the Actions token lacks the `workflow` scope). "
            f"No PR was opened — add them manually or provide a PAT with the "
            f"`workflow` scope."
        )
        print(f"⚠️ {note}")
        comment_on_issue(issue_number, note)
        return 0

    pr_title = data.get("pr_title") or f"fix: resolve issue #{issue_number}"
    pr_body = data.get("pr_description") or f"Automated PR for issue #{issue_number}."
    if f"#{issue_number}" not in pr_body:
        pr_body += f"\n\nFixes #{issue_number}"

    print(f"🌿 Opening PR for issue #{issue_number} …")
    ok, result = generator.open_pr(
        branch=f"auto-fix/issue-{issue_number}",
        title=pr_title,
        body=pr_body,
        file_changes=file_changes,
    )
    if ok:
        print(f"🎉 Pull Request created:\n{result}")
    else:
        print(f"⚠️ PR creation note: {result}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
