"""Automatic PR generator from GitHub Issues powered by Gemini 3.6."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from google import genai


def run_cmd(cmd: list[str]) -> str:
    res = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return res.stdout.strip()


def main() -> int:
    issue_number = os.environ.get("ISSUE_NUMBER")
    issue_title = os.environ.get("ISSUE_TITLE", "")
    issue_body = os.environ.get("ISSUE_BODY", "")

    if not issue_number:
        print("Error: ISSUE_NUMBER environment variable is required", file=sys.stderr)
        return 1

    print(f"🚀 Processing Issue #{issue_number}: {issue_title}")

    client = genai.Client()
    model_name = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")

    system_instruction = (
        "You are an expert AI software engineer. Given an issue title and description, "
        "analyze the task and generate the precise file changes needed to satisfy the issue. "
        "You MUST respond with a single JSON object containing:\n"
        "- 'pr_title': string (short conventional commit style PR title)\n"
        "- 'pr_description': string (clear explanation of changes made, ending with 'Fixes #<issue_number>')\n"
        "- 'file_changes': array of objects with 'path' (relative file path) and 'content' (full complete file contents)"
    )

    prompt = f"""
Issue #{issue_number}: {issue_title}

Issue Description:
{issue_body}

Please generate the file changes to solve this issue.
"""

    print(f"🤖 Generating solution using model '{model_name}' …")
    response = client.models.generate_content(
        model=model_name,
        contents=prompt,
        config={
            "system_instruction": system_instruction,
            "response_mime_type": "application/json",
        },
    )

    raw_text = response.text or "{}"
    if raw_text.startswith("```"):
        raw_text = raw_text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

    try:
        data = json.loads(raw_text)
    except json.JSONDecodeError as e:
        print(f"❌ Failed to parse JSON response from Gemini: {e}\nRaw output:\n{raw_text}", file=sys.stderr)
        return 1

    pr_title = data.get("pr_title", f"fix: resolve Issue #{issue_number} - {issue_title}")
    pr_body = data.get("pr_description", f"Automated PR generated for Issue #{issue_number}.\n\nFixes #{issue_number}")
    if f"#{issue_number}" not in pr_body:
        pr_body += f"\n\nFixes #{issue_number}"

    file_changes = data.get("file_changes", [])
    if not file_changes:
        print("⚠️ No file changes generated by the model.")
        return 0

    branch_name = f"auto-fix/issue-{issue_number}"

    print(f"🌿 Setting up branch '{branch_name}' and applying changes …")
    run_cmd(["git", "config", "user.name", "github-actions[bot]"])
    run_cmd(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"])
    run_cmd(["git", "checkout", "-b", branch_name])

    for change in file_changes:
        path = change["path"]
        content = change["content"]
        parent_dir = os.path.dirname(path)
        if parent_dir:
            os.makedirs(parent_dir, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        run_cmd(["git", "add", path])
        print(f"  ✓ Updated/Created: {path}")

    commit_msg = f"fix: resolve Issue #{issue_number}\n\n{issue_title}"
    run_cmd(["git", "commit", "-m", commit_msg])

    print(f"⬆️ Pushing branch '{branch_name}' to GitHub …")
    run_cmd(["git", "push", "-u", "origin", branch_name, "--force"])

    print("📬 Opening Pull Request …")
    res = subprocess.run(
        [
            "gh", "pr", "create",
            "--title", pr_title,
            "--body", pr_body,
            "--base", "main",
            "--head", branch_name,
        ],
        capture_output=True,
        text=True,
    )

    if res.returncode == 0:
        print(f"🎉 Pull Request created successfully!\n{res.stdout.strip()}")
    else:
        print(f"⚠️ PR creation note: {res.stderr.strip() or res.stdout.strip()}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
